/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FileSenderFrame.java
 *
 * Created on Jan 31, 2013, 9:14:28 PM
 */
package officecomunicator;

import java.io.File;
import javax.swing.JCheckBox;
import javax.swing.JFileChooser;
import javax.swing.text.html.HTMLEditorKit;

/**
 *
 * @author TOSHIBA
 */
public class FileSenderFrame extends javax.swing.JFrame {

    HTMLEditorKit text_panel_html_kit;
    OfficeFrame frS;

    public String getFileName() {
        return fileName;
    }

    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    public String getFilePath() {
        return filePath;
    }

    public void setFilePath(String filePath) {
        this.filePath = filePath;
    }
    String filePath;
    String fileName;

    /** Creates new form FileSenderFrame */
    public FileSenderFrame(OfficeFrame of) {
        initComponents();
        frS = of;
        setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        pathfile = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        swg = new javax.swing.JCheckBox();
        swaf = new javax.swing.JCheckBox();
        jButton2 = new javax.swing.JButton();
        prog = new javax.swing.JProgressBar();
        swf = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setTitle("File Sender");
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));

        pathfile.setEditable(false);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        swg.setText("Share with group");
        swg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                swgActionPerformed(evt);
            }
        });

        swaf.setSelected(true);
        swaf.setText("Send to all Controller");
        swaf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                swafActionPerformed(evt);
            }
        });

        jButton2.setText("Send");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        prog.setStringPainted(true);

        swf.setText("none");
        swf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                swfActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(153, 204, 0));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/officecomunicator/Jagannath_University_logo2.png"))); // NOI18N
        jLabel1.setText("Jagannath University");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(swg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(swaf, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2))
                    .addComponent(swf, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(pathfile, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(prog, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pathfile, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(swf, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(swg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(swaf))
                .addGap(10, 10, 10)
                .addComponent(prog, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            JFileChooser fc = new JFileChooser();
            fc.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
            int result = fc.showOpenDialog(this);
            if (result == JFileChooser.CANCEL_OPTION) {
            }
            File fileN = fc.getSelectedFile();
            if (fileN.exists()) {
                pathfile.setText("" + fileN.getPath());
                setFilePath(fileN.getPath());
                setFileName(fileN.getName());
            }
        } catch (Exception ex) {
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (swaf.isSelected()) {
            frS.setFilePath(filePath);
            frS.setFileName(fileName);
            //ServerFile sf = new ServerFile(frS.getFilePath(), frS.ts.server, frS.ts.socket, this);
            //frS.ts.sf = sf;
            frS.ts.setMsg("Rcv");
            frS.ts.writer();
        } else if (swg.isSelected()) {

            frS.setFilePath(filePath);
            frS.setFileName(fileName);
            //ServerFile sf = new ServerFile(frS.getFilePath(), frS.ts.server, frS.ts.socket, this);
            //frS.ts.sf = sf;
            frS.ts.setMsg("Rcv");
            frS.ts.GroupWriter();
        } else if (swf.isSelected()) {
            frS.setFilePath(filePath);
            frS.setFileName(fileName);
            //ServerFile sf = new ServerFile(frS.getFilePath(), frS.ts.server, frS.ts.socket, this);
            //frS.ts.sf = sf;
            frS.ts.setMsg("Rcv");
            frS.setChatafriend("" + frS.friendList.getSelectedValue());
            frS.ts.ChatAWriter();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void swgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_swgActionPerformed
        // TODO add your handling code here:
        if (swg.isSelected()) {
            if (swaf.isSelected() || swf.isSelected()) {
                clickAgain(swaf, swf);
            }
        }
    }//GEN-LAST:event_swgActionPerformed

    private void swafActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_swafActionPerformed
        // TODO add your handling code here:
        if (swaf.isSelected()) {
            if (swg.isSelected() || swf.isSelected()) {
                clickAgain(swg, swf);
            }
        }
    }//GEN-LAST:event_swafActionPerformed

    private void swfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_swfActionPerformed
        // TODO add your handling code here:
        if (swf.isSelected()) {
            if (swg.isSelected() || swaf.isSelected()) {
                clickAgain(swg, swaf);
            }
        }
    }//GEN-LAST:event_swfActionPerformed

    public void clickAgain(JCheckBox jCBA, JCheckBox jCBB) {
        if (jCBA.isSelected()) {
            jCBA.doClick();
        }
        if (jCBB.isSelected()) {
            jCBB.doClick();
        }
    }
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField pathfile;
    public javax.swing.JProgressBar prog;
    public javax.swing.JCheckBox swaf;
    public javax.swing.JCheckBox swf;
    private javax.swing.JCheckBox swg;
    // End of variables declaration//GEN-END:variables
}
