/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * OfficeFrame.java
 *
 * Created on Jan 18, 2013, 9:59:59 PM
 */
package officecomunicator;

import java.awt.Desktop;
import java.io.File;
import java.io.FileWriter;
import java.net.InetAddress;
import java.net.URI;
import java.util.Formatter;
import java.util.Scanner;
import javax.swing.ImageIcon;
import javax.swing.JCheckBox;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.text.html.HTMLDocument;
import javax.swing.text.html.HTMLEditorKit;

/**
 *
 * @author TOSHIBA
 */
public class OfficeFrame extends javax.swing.JFrame {

    ThreadServer ts;
    FileWriter savedName = null;
    Scanner readNames = null;
    public String Names[] = new String[1000];
    public int namesCounter = 0;
    public Formatter deleteAccount = null;
    public String delName;
    public int dontSave = 0;
    public int alreadyConnected = 0;
    public Thread ThSa;
    FileSenderFrame fsf;

    public String getFileName() {
        return FileName;
    }

    public void setFileName(String FileName) {
        this.FileName = FileName;
    }

    public String getFilePath() {
        return FilePath;
    }

    public void setFilePath(String FilePath) {
        this.FilePath = FilePath;
    }
    public String FilePath;
    public String FileName;

    public String getIpAccount() {
        return ipAccount;
    }

    public void setIpAccount(String ipAccount) {
        this.ipAccount = ipAccount;
    }

    public String getNameAccount() {
        return nameAccount;
    }

    public void setNameAccount(String nameAccount) {
        this.nameAccount = nameAccount;
    }
    public String nameAccount;
    public String ipAccount;

    public String getDeleteFriend() {
        return deleteFriend;
    }

    public void setDeleteFriend(String deleteFriend) {
        this.deleteFriend = deleteFriend;
    }
    public String deleteFriend;
    public String name;
    HTMLEditorKit text_panel_html_kit;

    public String getRemoveFriendGroup() {
        return removeFriendGroup;
    }

    public void setRemoveFriendGroup(String removeFriendGroup) {
        this.removeFriendGroup = removeFriendGroup;
    }
    public String removeFriendGroup;

    public String getChatafriend() {
        return chatafriend;
    }

    public void setChatafriend(String chatafriend) {
        this.chatafriend = chatafriend;
    }
    public String chatafriend;

    public String getLogInUser() {
        return logInUser;
    }

    public void setLogInUser(String logInUser) {
        this.logInUser = logInUser;
    }
    public String logInUser = null;

    public String getUserName() {
        return UserName;
    }

    public void setUserName(String UserName) {
        this.UserName = UserName;
    }
    public String UserName;

    /**
     * Creates new form OfficeFrame
     */
    public OfficeFrame() {
        initComponents();
        ts = new ThreadServer(this);
        ThSa = new Thread(ts);
        ThSa.start();
        creatForder();
        setLocationRelativeTo(null);
        //openIconFile();
        text_panel_html_kit = new HTMLEditorKit();
        output.setEditorKit(text_panel_html_kit);
        output.setDocument(new HTMLDocument());
        //jTextPane1.setText("<a href=\"http://www.w3schools.com/\">Visit W3Schools</a> ");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        output = new javax.swing.JTextPane();
        message = new javax.swing.JTextField();
        Gchat = new javax.swing.JCheckBox();
        chatFriend = new javax.swing.JCheckBox();
        chatAllFriend = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        friendList = new javax.swing.JList();
        jButton5 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        groupList = new javax.swing.JList();
        jButton4 = new javax.swing.JButton();
        RefreshAll = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        logOut = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("User");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        output.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "InBox", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Times New Roman", 0, 12))); // NOI18N
        output.setContentType("text/html"); // NOI18N
        output.setEditable(false);
        output.setFont(new java.awt.Font("Times New Roman", 0, 7)); // NOI18N
        jScrollPane1.setViewportView(output);

        message.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        message.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Send", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));
        message.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                messageActionPerformed(evt);
            }
        });

        Gchat.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        Gchat.setText("Group");
        Gchat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GchatActionPerformed(evt);
            }
        });

        chatFriend.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        chatFriend.setText("Selected One");
        chatFriend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chatFriendActionPerformed(evt);
            }
        });

        chatAllFriend.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        chatAllFriend.setSelected(true);
        chatAllFriend.setText("To All");
        chatAllFriend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chatAllFriendActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setText("Send To:");

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));

        friendList.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Connected Controllers", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 10))); // NOI18N
        friendList.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        friendList.setForeground(new java.awt.Color(0, 153, 0));
        jScrollPane2.setViewportView(friendList);

        jButton5.setFont(new java.awt.Font("Times New Roman", 0, 9)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/officecomunicator/rem.png"))); // NOI18N
        jButton5.setText("Remove");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Times New Roman", 0, 9)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/officecomunicator/add.png"))); // NOI18N
        jButton3.setText("Add to Group");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jScrollPane2)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));

        groupList.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Group List", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Times New Roman", 0, 10))); // NOI18N
        groupList.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        groupList.setForeground(new java.awt.Color(0, 204, 204));
        jScrollPane3.setViewportView(groupList);

        jButton4.setFont(new java.awt.Font("Times New Roman", 0, 9)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/officecomunicator/rem.png"))); // NOI18N
        jButton4.setText("Remove");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane3)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        RefreshAll.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        RefreshAll.setIcon(new javax.swing.ImageIcon(getClass().getResource("/officecomunicator/refresh.PNG"))); // NOI18N
        RefreshAll.setText("<html><b><u>R</u>efresh</b><br>All Lists</html>");
        RefreshAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshAllActionPerformed(evt);
            }
        });

        jCheckBox1.setSelected(true);
        jCheckBox1.setText("<html><b><u>A</u>lert Me</b><br>on Chat</html>");

        logOut.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        logOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/officecomunicator/endExam.PNG"))); // NOI18N
        logOut.setText("Log out");
        logOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addComponent(RefreshAll, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(logOut, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(RefreshAll, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jCheckBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(logOut, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Gchat, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chatFriend)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chatAllFriend)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 390, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(message)
                            .addComponent(jScrollPane1))
                        .addGap(10, 10, 10)))
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 499, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Gchat, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chatFriend)
                            .addComponent(chatAllFriend))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(message, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jMenu1.setText("Head Controller");

        jMenuItem3.setText("Log Out");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem5.setText("Refresh All List");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");

        jMenuItem1.setText("Credits");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void messageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_messageActionPerformed
        // TODO add your handling code here:
        if (chatAllFriend.isSelected()) {
            try {
                ts.setMsg("HHHHead Controller" + ": " + message.getText());
                ts.writer();
                //output.setText(output.getText() + "Controller: " + message.getText() + "\n");

                designer("User: " + message.getText(), "Fuchsia");

            } catch (Exception ex) {
                designer("Problem!!!! in chatting()Frame. unable to chat with the server " + ex, "red");
            }
            message.setText("");
        } else if (Gchat.isSelected()) {
            try {
                ts.setMsg("HHHHead Controller" + ": " + message.getText());
                ts.GroupWriter();
                //output.setText(output.getText() + "Controller: " + message.getText() + "\n");

                designer("User: " + message.getText(), "Fuchsia");

            } catch (Exception ex) {
                designer("Problem!!!! in chatting()Frame. unable to chat with the server " + ex, "red");
            }
            message.setText("");
        } else if (chatFriend.isSelected()) {
            if (friendList.getSelectedValue() != null) {
                setChatafriend("" + friendList.getSelectedValue());
                try {
                    ts.setMsg("HHHHead Controller" + ": " + message.getText());
                    ts.ChatAWriter();
                    //output.setText(output.getText() + "Controller: " + message.getText() + "\n");

                    designer("User: " + message.getText(), "Fuchsia");

                } catch (Exception ex) {
                    designer("Problem!!!! in chatting()Frame. unable to chat with the server " + ex, "red");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Please Select a friend from 'Connected Friend' List.");
            }
        }
    }//GEN-LAST:event_messageActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if (friendList.getSelectedValue() != null) {
            ts.friendGroup[ts.groupCounter] = "" + friendList.getSelectedValue();
            ts.groupCounter++;
            GroupListManeger();
        } else {
            JOptionPane.showMessageDialog(null, "Please select a friend from 'Connected Controller' list");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if (groupList.getSelectedValue() != null) {
            setRemoveFriendGroup("" + groupList.getSelectedValue());
            ts.removeFriendFromGroup();
        } else {
            JOptionPane.showMessageDialog(null, "Please Select a friend from 'Group List' List.");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void GchatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GchatActionPerformed
        // TODO add your handling code here:
        if (Gchat.isSelected()) {
            if (chatFriend.isSelected() || chatAllFriend.isSelected()) {
                clickAgain(chatFriend, chatAllFriend);
            }
        }
    }//GEN-LAST:event_GchatActionPerformed

    private void chatFriendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chatFriendActionPerformed
        // TODO add your handling code here:
        if (chatFriend.isSelected()) {
            if (Gchat.isSelected() || chatAllFriend.isSelected()) {
                clickAgain(Gchat, chatAllFriend);
            }
        }
    }//GEN-LAST:event_chatFriendActionPerformed

    private void chatAllFriendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chatAllFriendActionPerformed
        // TODO add your handling code here:
        if (chatAllFriend.isSelected()) {
            if (chatFriend.isSelected() || Gchat.isSelected()) {
                clickAgain(chatFriend, Gchat);
            }
        }
    }//GEN-LAST:event_chatAllFriendActionPerformed

    private void logOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutActionPerformed
        // TODO add your handling code here:
        ts.setMsg("Remove");
        ts.removewriter();
    }//GEN-LAST:event_logOutActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        HelpA hp = new HelpA();
        hp.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        logOutActionPerformed(evt);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        RefreshAllActionPerformed(evt);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void RefreshAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshAllActionPerformed
        // TODO add your handling code here:
        ListManeger();
        GroupListManeger();
}//GEN-LAST:event_RefreshAllActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        if (friendList.getSelectedValue() != null) {
            setDeleteFriend("" + friendList.getSelectedValue());
            ts.setMsg(getDeleteFriend());
            ts.writer();
            setRemoveFriendGroup(getDeleteFriend());
            ts.removeFriendFromGroup();
        } else {
            JOptionPane.showMessageDialog(null, "Please Select a Controller from 'Connected Controller' List.");
        }
}//GEN-LAST:event_jButton5ActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(null, "Do you want to exit?\nYou will be logged out...") < 1) {
            ts.setMsg("LogOut");
            ts.writer();
            try {
                Thread.sleep(2000);
            } catch (Exception ex) {
            }
            System.exit(0);
        } else {
        }
    }//GEN-LAST:event_formWindowClosing

    public void ListManeger() {
        String friName[] = new String[ts.getCancle()];
        int i = 0;
        for (i = 0; i < ts.getCancle(); i++) {
            friName[i] = ts.friendName[i];
        }

        friendList.setListData(friName);

        if (ts.getCancle() <= 0) {
            String a[] = new String[0];
            friendList.setListData(a);
        }
    }

    public void GroupListManeger() {
        String friName[] = new String[ts.getGroupCounter()];
        int i = 0;
        for (i = 0; i < ts.getGroupCounter(); i++) {
            friName[i] = ts.friendGroup[i];
        }

        groupList.setListData(friName);

        if (ts.getCancle() <= 0) {
            String a[] = new String[0];
            groupList.setListData(a);
        }
    }

    public void designer(String line, String col) {
        try {
            text_panel_html_kit.insertHTML((HTMLDocument) output.getDocument(), output.getDocument().getLength(), "<font size=7 color=" + col + ">" + line + "</font><font size=7 color=" + col + ">" + "</font>", 0, 0, null);
            //sR.recode.setText(sR.recode.getText() + line + "\n");
        } catch (Exception ex) {
        }
    }

    public void clickAgain(JCheckBox jCBA, JCheckBox jCBB) {
        if (jCBA.isSelected()) {
            jCBA.doClick();
        }
        if (jCBB.isSelected()) {
            jCBB.doClick();
        }
    }

    public void savedFriendFile() {
        try {
            savedName = new FileWriter(new File("C://OCS(Kotha)//" + getLogInUser() + "//Saved Names.doc"), true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error in saved Name file. " + ex);
        }
    }

    public void closeSavedFriendFile() {
        try {
            savedName.close();
        } catch (Exception ex) {
        }
    }

    public void creatForder() {
        File folder = new File("D://Head Controller");
        if (!folder.exists()) {
            folder.mkdir();
        }
        File rcvfolder = new File("D://Head Controller/Received file");
        if (!rcvfolder.exists()) {
            rcvfolder.mkdir();
        }
    }

    public void deleteFromSavedAccount() {
        try {
            deleteAccount = new Formatter(new File("C://OCS(Kotha)//" + getLogInUser() + "//Saved Names.doc"));
            for (int a = 0; a < namesCounter; a++) {
                if (Names[a].equals(delName)) {
                } else {
                    deleteAccount.format("%s\n", Names[a]);
                }
            }
            deleteAccount.close();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error to delete. " + ex);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OfficeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OfficeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OfficeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OfficeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new OfficeFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JCheckBox Gchat;
    private javax.swing.JButton RefreshAll;
    public javax.swing.JCheckBox chatAllFriend;
    public javax.swing.JCheckBox chatFriend;
    public javax.swing.JList friendList;
    private javax.swing.JList groupList;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    public javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton logOut;
    public javax.swing.JTextField message;
    public javax.swing.JTextPane output;
    // End of variables declaration//GEN-END:variables
}
